apiVersion: v1
kind: Service
metadata:
  name: mongo-master-svc
  labels:
    app: mongo
    role: master
    tier: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
    role: master
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-master-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: foxley-moods-api
  labels:
    app: mongo
    tier: database
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 3000
  selector:
    app: mongo
    tier: database
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foxley-moods-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
        tier: database
    spec:
      containers:
      - name: nodejs-moods-api
        image: 696251787677.dkr.ecr.us-west-2.amazonaws.com/foxley/moods-api
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 3000